{% set name = "dask-kubernetes" %}
{% set version = "2022.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-kubernetes-{{ version }}.tar.gz
  sha256: ff34d71b1d7dec6cbcba3a99db3b0d1a326cc50f9d2090ee8d85508a3f776d45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask-core >=2022.08.1
    - distributed >=2022.08.1
    - python-kubernetes >=12.0.1
    - kubernetes_asyncio >=12.0.1
    - kopf >=1.35.3

test:
  imports:
    - dask_kubernetes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/dask-kubernetes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Native Kubernetes integration for Dask

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
    - jacobtomlinson
