{% set version = "0.10.1" %}

package:
  name: dask-kubernetes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-kubernetes/dask-kubernetes-{{ version }}.tar.gz
  sha256: 9d9a8fca96650083827cc62735f6a860c9340f92ea3cf34c01881c6bd40f004f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - dask-core >=2.5.2
    - distributed >=2.5.2
    - python-kubernetes >=9
    - kubernetes_asyncio >=9

test:
  imports:
    - dask_kubernetes

about:
  home: https://github.com/dask/dask-kubernetes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Native Kubernetes integration for Dask

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
    - jacobtomlinson
