{% set version = "2022.5.1" %}

package:
  name: dask-kubernetes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-kubernetes/dask-kubernetes-{{ version }}.tar.gz
  sha256: 6f4a766a0c1b07bcadf78184a61cc64513f514a4ed6b016f325f5c7b7e91e757

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.5
    - dask-core >=2021.02.0
    - distributed >=2021.02.0
    - python-kubernetes >=12.0.1
    - kubernetes_asyncio >12.0.1
    - kopf >=1.35.3

test:
  imports:
    - dask_kubernetes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/dask-kubernetes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Native Kubernetes integration for Dask

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
    - jacobtomlinson
