travis:
  secure:
    BINSTAR_TOKEN: P8O1bV+lANACgbxg8Y9aaCgWmXuEulSiofz0a+Z1XQ0IHsSefLSgHMqdr/sc71joFXWSy6iabWANEy/5LGAtYXg7BTTa7q3MabvzBiDjnNez+EqQW/JcrVUzWMpp8S5SpugKCNMW475riufx7ppSp/NcgFX8FrN8TZPaQc2IVUJKvYYXnx2Zm0QsQlkzsnWS6hAX57mphv6kC8U32m82CzSrLQ5OKwsaIeMZb13uqAPy/MllStlrFdhp4sHyYXQk7TIQd+wjB6h2Z9IYmzlETqYNVPvzmZs32jLDvtshit6q4dP3VoMlLiMM3u+fsirWJsKKHhp26PGJO6If1/4QAyDZunG5ZB84tP/hoMZP+QlqW9SvsnNG5UcD65iQIIM5gw/QkcOrKxikDHxYsjHOhE/M4Xb1R74+c2jQ3uz0MowbEV+lUR5XhAK3p4F2Wusj4QborZWE9rThSjZ2t0xGmvqeFDihNQQPlM/a+fMAMhqX1x74t755P3hReY2JvesvU982xIPxoi5G0ObF4z9TrJ9+5L5uZ3ZlzW/U1TMVWnlFoatXNRjKAxyWc5vi6tB8gXSMhacVQj+vx6U0JaSxF88V9tJLLXlFLFYbadUfDnRgvc8DZQOxT6ZPTki60fNSkkl7zuzX1loCTLd+WJKxuoBjjphl7A4RXVImUrchrEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
