travis:
  secure:
    BINSTAR_TOKEN: Rzz6RySTzo0gjIr8vPlc8/c1ju2orvJc3M79Wz18iBYnVSUWpDgP3SSSIwoHwKdUPHjeF6Tlaq0I2uo9yClcPZnLsebj+1wX9TXVywLBfFHLfB3mc67+HcEcLAo6Jy8B5/a7QIK8D0XxEmfxK02qSGTsESfXdIenUDgrorqKk+kSygXbZFdsvzHJFWaKGjbPXPqE7rGeHn2MqghwX96RHHOi9naq6deMule2Eonkzjad1xMhOV//icvzWV/S4I8xCUfaHJl5KLIv09HB8nfVFw1YJFxGsm1ALv1KV4VkmiuDtur47bfz5Rh6eLgenwo4wmbgHp4c1ww/y6q4HnrRoQ75Jhp4ZR+U7DJf3anjmAYpGyJoZmnaWtHzcIfwPJoEPchhQpCu/SofyVd/KKMMCmI9jE6tGs3AJW7D/0NIJmb0riM7ZuJxFQnYFYaJpQqxK1zQhypyFHo9LrCXrsfsBiQvU11aLV+3PpAROC5dqETkpCyeCz15KM5iOeUo6ikHgVyt3RWNF6jOv3QN2AER0y5BIBYQiyN3BR1bkhTOVRVuH9V8r0vFQJsbMaqXahSJmwGU/eoN01Tsqwt5NdKtcGzMp00qR2+QZPIU6OR5jywbZbZYtGbEK93HNV43ynEuYiu6C+SeWIDELKRWPLWKceSiNbcw5n3cMGE9QakXiv0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
